#!/bin/bash
echo
echo "================================="
echo "emonPi update started"
echo "================================="
echo
echo "EUID: $EUID"
echo

sudo pip install paho-mqtt --upgrade

#########################################################################################################
sudo /etc/init.d/emonhub stop

# Start ATmega328 serial upload using avrdude with latest hex available on github
/home/pi/emonpi/./update_emonPi.sh

sudo /etc/init.d/emonhub start
#########################################################################################################

# Add bash prompt RW / RO emonPi file-system indicator
if ! grep -q "# emonPi bash RW / RO prompt"  /etc/bash.bashrc ; then
        echo "Add RW bash prompt indicator"
        sudo bash -c 'cat /home/pi/emonpi/bash-rw-indicator >> /etc/bash.bashrc'
fi

#########################################################################################################

# Move ~/.npm folder to RW folder ~/data/npm to allow npm packages to be installed when emonPi is in RO mode

if [ ! -d /home/pi/data/npm ]; then
  echo "moving ~./npm to ~/data/npm and create symlink"
  mv /home/pi/.npm /home/pi/data/npm
  ln -s /home/pi/data/npm /home/pi/.npm
fi

#########################################################################################################

# Install / update nodeRED  emonPixel & Emoncms nodes

cd /home/pi/.node-red
npm install https://github.com/openenergymonitor/node-red-contrib-emonpixel
npm install node-red-node-emoncms
cd /home/pi