#!/bin/sh
sudo mount -o remount,rw /dev/mmcblk0p2  /
echo "\033[01;32mFilesystem is unlocked - Write access"
echo "\033[01;31mtype 'rpi-ro' to lock"
sudo sh -c "echo $(date) rw >> /home/pi/data/shared/ro-rw.log"

